{ config, pkgs, lib, ... }:

let
  # Путь к literate-файлу (редактируйте под себя)
  litOrg = "${config.home.homeDirectory}/System-configuration/home/navi/programs/emacs/config.org";
  repoConfig = "${config.home.homeDirectory}/System-configuration/home/navi/programs/emacs/config.el";

  initEl = ''
    ;;; init.el --- generated by Nix  -*- lexical-binding: t; -*-

    ;; Robust loader for literate config:
    ;; 1) prefer ~/.emacs.d/config.el (home-manager generated)
    ;; 2) last resort: tangle config.org -> ~/.emacs.d/config.el and load

    (let* ((tangled (expand-file-name "config.el" user-emacs-directory))
           (repo    "${repoConfig}")
           (orgfile "${litOrg}"))
      (cond
       ;; 1) If the tangled config exists, load it (normal HM flow).
       ((file-exists-p tangled)
        (condition-case err
            (progn (load tangled nil 'nomessage)
                   (message "Loaded %s" tangled))
          (error (message "Error loading %s: %S" tangled err))))

       ;; 3) Otherwise, try to tangle the literate org file into ~/.emacs.d/config.el
       ((file-exists-p orgfile)
        (condition-case err
            (progn
              (require 'org)
              (require 'ob-tangle)
              (let ((org-confirm-babel-evaluate nil))
                (org-babel-tangle-file orgfile tangled))
              (if (file-exists-p tangled)
                  (progn (load tangled nil 'nomessage)
                         (message "Tangled and loaded %s" tangled))
                (message "Tangle did not produce %s" tangled)))
          (error (message "Tangle/load failed: %S" err))))

       ;; Nothing found — show helpful message but don't abort Emacs.
       (t (message "No Emacs config found. Tried: %s, %s, %s" tangled repo orgfile))))
  '';
in
{
  home.packages = [ pkgs.emacs ];

  # NOTE: we no longer create ~/.emacs.d/init.el via home.file (that caused /nix/store immutability).
  # Instead we tangle config.org (below) and *write* init.el into $HOME during activation.

  # Тэнглим literate-org в ~/.emacs.d/config.el при каждом `home-manager switch`
  home.activation.tangleEmacsConfig =
    lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      if [ -f "${litOrg}" ]; then
        ${pkgs.emacs}/bin/emacs --batch \
          --eval "(require 'org)" \
          --eval "(require 'ob-tangle)" \
          --eval '(org-babel-tangle-file
                    "${litOrg}"
                    (expand-file-name "config.el" "~/.emacs.d/"))'
      else
        echo "WARN: Literate Org not found at ${litOrg}; skipping tangle." >&2
      fi
    '';

  # Записываем init.el *в домашнюю папку* после тэнглинга, чтобы Emacs мог модифицировать/устанавливать пакеты
  home.activation.writeInit =
    lib.hm.dag.entryAfter [ "tangleEmacsConfig" ] ''
      mkdir -p "${config.home.homeDirectory}/.emacs.d"
      # Записываем init.el (содержимое вставляется из переменной initEl)
      cat > "${config.home.homeDirectory}/.emacs.d/init.el" <<'INIT'
${initEl}
INIT
      echo "Wrote ~/.emacs.d/init.el"
    '';
}
